const products = [
    {
        id: 1, 
        name: "Hand-Painted Vase", 
        price: 45, 
        artisan: "Elena Rodriguez", 
        category: "pottery", 
        region: "mx", 
        material: "clay", 
        gender: "women", 
        isFairTrade: true, 
        isCarbonNeutral: false, 
        sustainabilityMetric: "Organic", 
        image: "assets/images/product1.webp",
        rating: 4.8,
        description: "Beautifully hand-painted ceramic vase with traditional Mexican patterns"
    },
    {
        id: 2, 
        name: "Eco-Friendly Yoga Mat", 
        price: 75, 
        artisan: "Aisha Khan", 
        category: "yoga", 
        region: "in", 
        material: "cotton", 
        gender: "women", 
        isFairTrade: true, 
        isCarbonNeutral: true, 
        sustainabilityMetric: "Biodegradable", 
        image: "assets/images/product2.webp",
        rating: 4.9,
        description: "Sustainable yoga mat made from organic cotton and natural rubber"
    },
    {
        id: 3, 
        name: "Artisan Coffee Blend", 
        price: 22, 
        artisan: "Marco Rossi", 
        category: "organic", 
        region: "it", 
        material: "herbs", 
        gender: "men", 
        isFairTrade: true, 
        isCarbonNeutral: false, 
        sustainabilityMetric: "Organic", 
        image: "assets/images/product3.webp",
        rating: 4.7,
        description: "Premium organic coffee blend from Italian highlands"
    },
    {
        id: 4, 
        name: "Handwoven Scarf", 
        price: 55, 
        artisan: "Sofia Petrova", 
        category: "accessories", 
        region: "vn", 
        material: "cotton", 
        gender: "women", 
        isFairTrade: true, 
        isCarbonNeutral: false, 
        sustainabilityMetric: "Handcrafted", 
        image: "assets/images/product4.webp",
        rating: 4.6,
        description: "Elegant handwoven scarf with traditional Vietnamese patterns"
    },
    {
        id: 5, 
        name: "Clay & Herb Infuser", 
        price: 30, 
        artisan: "Wei Chen", 
        category: "herbal", 
        region: "cn", 
        material: "clay", 
        gender: "men", 
        isFairTrade: false, 
        isCarbonNeutral: false, 
        sustainabilityMetric: "Handcrafted", 
        image: "assets/images/product5.webp",
        rating: 4.5,
        description: "Traditional clay tea infuser perfect for herbal teas"
    },
    {
        id: 6, 
        name: "Regional Spice Set", 
        price: 40, 
        artisan: "Javier Morales", 
        category: "regional", 
        region: "mx", 
        material: "herbs", 
        gender: "men", 
        isFairTrade: true, 
        isCarbonNeutral: true, 
        sustainabilityMetric: "Organic", 
        image: "assets/images/product6.webp",
        rating: 4.8,
        description: "Authentic Mexican spice collection from local markets"
    },
    {
        id: 7, 
        name: "Carved Wooden Bowl", 
        price: 120, 
        artisan: "Lena Schmidt", 
        category: "woodwork", 
        region: "de", 
        material: "wood", 
        gender: "women", 
        isFairTrade: false, 
        isCarbonNeutral: false, 
        sustainabilityMetric: "Biodegradable", 
        image: "assets/images/product7.webp",
        rating: 4.9,
        description: "Intricately carved wooden bowl from sustainable German forests"
    },
    {
        id: 8, 
        name: "Ceramic Tea Set", 
        price: 95, 
        artisan: "Kenji Tanaka", 
        category: "pottery", 
        region: "jp", 
        material: "clay", 
        gender: "men", 
        isFairTrade: true, 
        isCarbonNeutral: true, 
        sustainabilityMetric: "Handcrafted", 
        image: "assets/images/product8.webp",
        rating: 5.0,
        description: "Traditional Japanese ceramic tea set with minimalist design"
    },
    {
        id: 9, 
        name: "Hand-Stitched Quilt", 
        price: 210, 
        artisan: "Anya Petrova", 
        category: "accessories", 
        region: "ru", 
        material: "cotton", 
        gender: "women", 
        isFairTrade: false, 
        isCarbonNeutral: true, 
        sustainabilityMetric: "Handcrafted", 
        image: "assets/images/product9.webp",
        rating: 4.7,
        description: "Warm, hand-stitched quilt with traditional Russian patterns"
    },
    {
        id: 10, 
        name: "Essential Oil Diffuser", 
        price: 65, 
        artisan: "Chloé Dubois", 
        category: "herbal", 
        region: "fr", 
        material: "wood", 
        gender: "women", 
        isFairTrade: true, 
        isCarbonNeutral: false, 
        sustainabilityMetric: "Biodegradable", 
        image: "assets/images/product10.webp",
        rating: 4.6,
        description: "Elegant wooden essential oil diffuser with French craftsmanship"
    },
    {
        id: 11, 
        name: "Peruvian Loom", 
        price: 110, 
        artisan: "Maria Flores", 
        category: "accessories", 
        region: "pe", 
        material: "cotton", 
        gender: "women", 
        isFairTrade: true, 
        isCarbonNeutral: true, 
        sustainabilityMetric: "Handcrafted", 
        image: "assets/images/product11.webp",
        rating: 4.8,
        description: "Traditional Peruvian loom for creating beautiful textiles"
    },
    {
        id: 12, 
        name: "Eco-friendly Basket", 
        price: 45, 
        artisan: "Sanjay Patel", 
        category: "home", 
        region: "in", 
        material: "jute", 
        gender: "men", 
        isFairTrade: true, 
        isCarbonNeutral: false, 
        sustainabilityMetric: "Biodegradable", 
        image: "assets/images/product12.webp",
        rating: 4.5,
        description: "Sustainable jute basket perfect for storage and organization"
    },
    // Additional products for better recommendations
    {
        id: 13, 
        name: "Bamboo Water Bottle", 
        price: 35, 
        artisan: "Lin Zhang", 
        category: "wellness", 
        region: "cn", 
        material: "wood", 
        gender: "unisex", 
        isFairTrade: true, 
        isCarbonNeutral: true, 
        sustainabilityMetric: "Eco-Friendly", 
        image: "assets/images/product13.webp",
        rating: 4.4,
        description: "Sustainable bamboo water bottle with natural insulation"
    },
    {
        id: 14, 
        name: "Organic Cotton T-Shirt", 
        price: 28, 
        artisan: "James Wilson", 
        category: "men", 
        region: "us", 
        material: "cotton", 
        gender: "men", 
        isFairTrade: true, 
        isCarbonNeutral: false, 
        sustainabilityMetric: "Organic", 
        image: "assets/images/product14.webp",
        rating: 4.3,
        description: "Comfortable organic cotton t-shirt with ethical production"
    },
    {
        id: 15, 
        name: "Silk Meditation Cushion", 
        price: 89, 
        artisan: "Priya Sharma", 
        category: "yoga", 
        region: "in", 
        material: "cotton", 
        gender: "unisex", 
        isFairTrade: true, 
        isCarbonNeutral: true, 
        sustainabilityMetric: "Handcrafted", 
        image: "assets/images/product15.webp",
        rating: 4.9,
        description: "Premium meditation cushion filled with organic buckwheat hulls"
    }
];

const artisans = [
  {
    id: 1,
    name: "Elena Rodriguez",
    location: "Oaxaca, Mexico",
    bio: "Traditional oaxacan pottery artist with a modern touch.",
    badge: "Fair Trade",
    gender: "women",
    image: "assets/images/artisan1.webp",
    specialties: ["pottery", "ceramics", "traditional art"],
    yearsExperience: 15,
    productsCount: 8
  },
  {
    id: 2,
    name: "Aisha Khan",
    location: "Kerala, India",
    bio: "Eco-friendly wellness crafts inspired by Ayurveda.",
    badge: "Eco-Friendly",
    gender: "women",
    image: "assets/images/artisan2.webp",
    specialties: ["yoga", "wellness", "eco-friendly"],
    yearsExperience: 12,
    productsCount: 6
  },
  {
    id: 3,
    name: "Marco Rossi",
    location: "Tuscany, Italy",
    bio: "Organic coffee blends crafted with Italian passion.",
    badge: "Organic Certified",
    gender: "men",
    image: "assets/images/artisan3.webp",
    specialties: ["organic", "coffee", "food"],
    yearsExperience: 20,
    productsCount: 4
  }

]